# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacked', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
